#运行参数配置
server:
  port: 8080
#数据库配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/xiaowa
    username: root
    password: sa123
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true #下划线自动转驼峰

#日志 显示sql
logging:
  level:
    org.zcx.userdemo.DAO: debug

#分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  pageSizeZero: true
  params: pageNum=start;pageSize=limit;count=countSql;
  rowBoundsWithCount: true
  offsetAsPageNum: false